import type { Metadata } from 'next';
import ServicePageTemplate from '@/components/ServicePageTemplate';

export const metadata: Metadata = {
  title: 'Performance Marketing in Bhubaneswar — Google, Meta & YouTube Ads | Marketing Copilot',
  description: 'Scale your revenue with high-velocity performance marketing in Bhubaneswar by Marketing Copilot. Omnichannel Google, Meta, and YouTube campaigns tied directly to profit.',
};

export default function PerformanceMarketingPage() {
  return (
    <ServicePageTemplate
      eyebrow="Performance Marketing — Bhubaneswar"
      title={`Grow your<br />Bhubaneswar business<br /><span class='accent-gradient'>with every rupee.</span>`}
      subtitle="Full-funnel cross-channel paid media architecture tied directly to net profit."
      description="We engineer multi-channel performance marketing engines that transform your ad budget into predictable, compounding revenue. By harmonizing Google Search, Meta Ads, YouTube, and LinkedIn with server-side attribution, we maximize your Return on Ad Spend (ROAS) across Bhubaneswar and Pan-India."
      emoji="📊"
      color="#0B2093"
      heroImage="https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1000&q=80"
      spotlightImage="https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1000&q=80"
      metrics={[
        { val: '5.6X', label: 'Blended ROAS' },
        { val: '-36%', label: 'Customer Acquisition Cost' },
        { val: '₹25Cr+', label: 'Media Budget Managed' },
      ]}
      localAdvantages={[
        {
          badge: 'Revenue Over Vanity',
          title: 'Contribution Margin Bidding',
          desc: 'We don’t optimize for cheap clicks or superficial reach. We optimize for actual revenue, gross margin, and bottom-line bank deposits in your Bhubaneswar business.',
        },
        {
          badge: 'Unified Cross-Channel',
          title: 'Google + Meta Synchronization',
          desc: 'Meta Ads creates awareness while Google Search captures the high-intent conversion. Cross-channel retargeting ensures zero leads slip through the cracks.',
        },
        {
          badge: 'Live Attribution',
          title: 'Real-Time Looker Studio Dashboards',
          desc: 'Access your 24/7 custom analytics dashboard showing live spend, cost-per-lead, conversion rates, and exact revenue generated by channel.',
        },
      ]}
      services={[
        {
          title: 'Omnichannel Media Planning & Budgeting',
          desc: 'Scientific allocation of monthly media budgets across Google, Meta, and LinkedIn based on incremental return rather than guesswork.',
          deliverables: ['Cross-Channel Media Plan', 'Channel Contribution Forecasting', 'Pacing & Spend Controls', 'Risk Hedging Architecture'],
        },
        {
          title: 'High-Intent Search & Shopping Dominance',
          desc: 'Capture ready buyers in Bhubaneswar searching for high-ticket commercial, real estate, and healthcare services on Google Search.',
          deliverables: ['Exact Match Keyword Bidding', 'Negative Keyword Lists', 'Quality Score Maximization', 'Shopping Feed Optimization'],
        },
        {
          title: 'Full-Funnel Social Acquisition (Meta & LinkedIn)',
          desc: 'Drive cold prospects from initial video Reel curiosity into instant lead form completions and booked consultations.',
          deliverables: ['Cold Prospecting Sets', 'Middle-of-Funnel Consideration', 'Bottom-of-Funnel Retargeting', 'B2B Account-Based Marketing'],
        },
        {
          title: 'Server-Side Tracking & First-Party Data',
          desc: 'Implement server-to-server Conversions API and Google Tag Manager containers that accurately track 100% of user touchpoints.',
          deliverables: ['Meta CAPI Configuration', 'GA4 Server-Side Events', 'Enhanced Conversions for Google', 'Attribution Modeling'],
        },
        {
          title: 'Rapid Creative Variation Testing',
          desc: 'Weekly testing of new visual hooks, headline angles, and call-to-action buttons to defeat creative fatigue and lower acquisition costs.',
          deliverables: ['Weekly Hook Variation Sprints', 'Dynamic Creative Optimization', 'UGC Video Formats', 'Motion Design Assets'],
        },
        {
          title: 'Post-Click Landing Page Optimization',
          desc: 'Traffic is only half the equation. We build fast, frictionless landing pages with psychological trust signals that maximize lead conversion.',
          deliverables: ['Sub-Second Load Times', '1-Click WhatsApp Prompts', 'Multi-Step Form Logic', 'Heatmap User Recordings'],
        },
      ]}
      caseHighlight={{
        client: 'Kalinga Auto Logistics & Commercial Vehicle Group',
        location: 'Rasulgarh & Mancheswar Industrial Estate, Bhubaneswar',
        metric: '7.2X ROAS',
        metricLabel: 'Generated Over ₹1.8 Crore in Verified Commercial Sales',
        summary: 'Marketing Copilot deployed combined Google Ads Search campaigns targeting fleet buyers and LinkedIn B2B campaigns reaching logistics directors. Generated 80+ high-ticket equipment lease inquiries per month.',
      }}
      process={[
        { step: '01', title: 'Financial & Unit Economic Audit', desc: 'Calculating your customer lifetime value, margins, and allowable cost-per-acquisition.' },
        { step: '02', title: 'Tracking & Tracking Architecture', desc: 'Deploying server-side pixels and GA4 conversion tracking before spending a single rupee.' },
        { step: '03', title: 'Multi-Channel Campaign Launch', desc: 'Activating Search, Social, and Retargeting campaigns with distinct creative angles.' },
        { step: '04', title: 'Bi-Weekly Iteration & Scale', desc: 'Aggressively shifting budget to highest-margin channels and scaling profitable ad sets.' },
      ]}
      platforms={['Google Ads', 'Meta Ads Manager', 'LinkedIn Campaign Manager', 'YouTube Ads', 'Google Tag Manager', 'GA4', 'Looker Studio', 'AppsFlyer']}
      faqs={[
        {
          q: 'What is performance marketing, and how does it differ from regular digital marketing?',
          a: 'Traditional digital marketing often focuses on vanity metrics like impressions, post likes, and follower counts. Performance marketing focuses strictly on measurable financial outcomes: cost per lead (CPL), customer acquisition cost (CAC), and Return on Ad Spend (ROAS).',
        },
        {
          q: 'What kind of businesses in Bhubaneswar benefit most from performance marketing?',
          a: 'Businesses with clear unit economics thrive on performance marketing — including real estate builders, hospitals, dental clinics, educational institutes, e-commerce brands, B2B manufacturing, and high-ticket service companies.',
        },
        {
          q: 'How often do we review campaign performance and metrics?',
          a: 'We provide you with 24/7 access to live Looker Studio dashboards, conduct weekly optimization sprints, and hold bi-weekly or monthly strategy reviews with our senior growth leads.',
        },
        {
          q: 'How quickly can we scale up our ad spend once a campaign is profitable?',
          a: 'Once we establish a stable, profitable cost-per-lead (CPL) during the initial testing phase, we can systematically scale budgets by 20% to 30% weekly without breaking algorithmic performance.',
        },
      ]}
    />
  );
}
