export interface IndustryItem {
  id: string;
  num: string;
  title: string;
  shortTitle: string;
  category: string;
  group: 'property' | 'health_edu' | 'retail_food' | 'b2b_industrial' | 'tech_logistics';
  tagline: string;
  desc: string;
  image: string;
  color: string;
  accentBg: string;
  badge: string;
  metric: string;
  metricLabel: string;
  services: string[];
  playbook: {
    bottlenecks: string[];
    solutions: string[];
    funnelSteps: { title: string; desc: string }[];
    benchmarks: { label: string; val: string }[];
    clientAnchor: string;
    clientLocation: string;
  };
}

export const industryCatalog: IndustryItem[] = [
  {
    id: 'real-estate',
    num: '01',
    title: 'Real Estate & Luxury Housing',
    shortTitle: 'Real Estate',
    category: 'HIGH-TICKET ASSET SALES',
    group: 'property',
    tagline: 'Generate high-intent apartment and villa buyers across Patia, Khandagiri, and Jaydev Vihar.',
    desc: 'Local SEO, precision Google Search Ads, and high-converting virtual tour landing pages that eliminate broker dependency and fill your sales pipeline with verified buyers.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
    color: '#0B2093',
    accentBg: 'rgba(11, 32, 147, 0.08)',
    badge: '3X INBOUND BUYERS',
    metric: '90+',
    metricLabel: 'Verified Inbound Buyers / Mo',
    services: ['Local SEO & Google 3-Pack', 'Google High-Intent Search Ads', 'Meta Virtual Tour Funnels', 'Sub-Second Next.js Landers'],
    playbook: {
      bottlenecks: [
        'Paying 2-3% brokerage to aggregators who sell the exact same leads to 5 competing builders.',
        'High bounce rates on slow builder websites loaded with uncompressed 50MB PDF brochures.',
        'Unqualified tire-kickers and low-budget inquiries clogging up the sales team’s day.',
      ],
      solutions: [
        'Proprietary hyperlocal SEO dominating searches like "3 BHK Luxury Flats in Patia" and "Villas near Infocity".',
        'Next.js 15 landing pages loading in under 0.8s with interactive 3D floorplan tours and instant WhatsApp scheduling.',
        'Two-step verification funnels filtering buyers by budget and purchase timeframe before notifying sales reps.',
      ],
      funnelSteps: [
        { title: 'Hyperlocal Intent Sniping', desc: 'Capture active home searchers on Google with negative keyword filters eliminating rental searches.' },
        { title: 'Interactive Virtual Showcase', desc: 'Engage serious buyers with 360-degree walkthroughs and price-bracket self-qualifiers.' },
        { title: 'Instant Site-Visit Booking', desc: 'Direct WhatsApp counselor integration booking verified weekend walkthroughs.' },
      ],
      benchmarks: [
        { label: 'Site Visit Conversion', val: '28.4%' },
        { label: 'Average Cost Per Site Visit', val: '₹420' },
        { label: 'Brokerage Elimination', val: '100%' },
      ],
      clientAnchor: 'Utkal Heights & Luxury Villas',
      clientLocation: 'Patia & Khandagiri, Bhubaneswar',
    },
  },
  {
    id: 'healthcare',
    num: '02',
    title: 'Healthcare, Clinics & Diagnostics',
    shortTitle: 'Healthcare',
    category: 'PATIENT TRUST & LOCAL 3-PACK',
    group: 'health_edu',
    tagline: 'Attract patients across Bhubaneswar with Google Maps 3-Pack dominance and appointment funnels.',
    desc: 'Patient review velocity, Google Business Profile acceleration, and doctor appointment booking funnels for multi-speciality hospitals, dental clinics, and diagnostic chains in Odisha.',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1000&q=80',
    color: '#059669',
    accentBg: 'rgba(5, 150, 105, 0.08)',
    badge: 'TOP 3 MAPS DOMINANCE',
    metric: '+190%',
    metricLabel: 'Direct Patient Calls',
    services: ['Google Maps 3-Pack SEO', 'Doctor GBP Optimization', 'WhatsApp Appointment Bot', 'Patient Review Velocity System'],
    playbook: {
      bottlenecks: [
        'Low visibility on Google Maps when patients search "Best Orthopedic Doctor near me" or "Saheed Nagar Dental Clinic".',
        'Patients booking appointments on third-party aggregators who charge heavy commissions per consultation.',
        'High no-show rates for diagnostic and OPD appointments.',
      ],
      solutions: [
        'Dominating Google Maps 3-Pack across 12 geo-fenced Bhubaneswar pin codes with automated review velocity.',
        'Direct 1-click WhatsApp appointment booking widget with automated reminder sequences reducing no-shows by 74%.',
        'Localized medical condition blogs and schema markup answering patient queries before competitors.',
      ],
      funnelSteps: [
        { title: 'Google Maps 3-Pack Anchor', desc: 'Optimized local citations and verified doctor profiles ranking for symptom searches.' },
        { title: 'Symptom-to-Specialist Funnel', desc: 'Clear treatment landing pages with doctor credentials, patient testimonials, and pricing clarity.' },
        { title: 'WhatsApp Automated Reminders', desc: 'Automated 2-hour and 24-hour reminder pings ensuring prompt clinic arrivals.' },
      ],
      benchmarks: [
        { label: 'Map View Growth', val: '+340%' },
        { label: 'Patient No-Show Rate', val: '< 6%' },
        { label: 'Direct OPD Consultations', val: '450+/Mo' },
      ],
      clientAnchor: 'CareFirst Multi-Speciality Clinic',
      clientLocation: 'Saheed Nagar, Bhubaneswar',
    },
  },
  {
    id: 'education',
    num: '03',
    title: 'Higher Education & Coaching',
    shortTitle: 'Education',
    category: 'STUDENT ENROLLMENT ACCELERATION',
    group: 'health_edu',
    tagline: 'Fill your classrooms with qualified student admissions from Bhubaneswar, Cuttack, and across Odisha.',
    desc: 'High-converting Meta ads, YouTube video storytelling, admission SEO clusters, and automated WhatsApp counseling funnels that scale student enrollments at an unheard-of CPL.',
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1000&q=80',
    color: '#4F46E5',
    accentBg: 'rgba(79, 70, 229, 0.08)',
    badge: '₹140 VERIFIED CPL',
    metric: '400+',
    metricLabel: 'Competitive Batch Admissions',
    services: ['Meta Student Lead Ads', 'YouTube Faculty Showcases', 'Course Curriculum SEO', 'WhatsApp Counselor CRM'],
    playbook: {
      bottlenecks: [
        'Seasonal rush leads to massive ad-spend spikes and exhausted counselors chasing unverified numbers.',
        'Parents hesitant to enroll without clear faculty credentials, previous results, and scholarship options.',
        'Delayed counselor response times causing interested students to join competing institutes.',
      ],
      solutions: [
        'Always-on digital counseling funnels running year-round with automated scholarship aptitude tests.',
        'Dynamic WhatsApp chatbot qualifying students by target exam (NEET, JEE, Civil Services) within 5 seconds.',
        'Faculty interview videos and previous topper showcase campaigns deployed across YouTube and Instagram.',
      ],
      funnelSteps: [
        { title: 'Aptitude Test Lead Magnet', desc: 'Free online scholarship test collecting verified parent and student contact details.' },
        { title: 'Instant Score & WhatsApp Report', desc: 'Counselor CRM receives score bracket instantly and delivers personalized career advice.' },
        { title: 'Campus Visit Invitation', desc: 'VIP invitation for classroom demo and faculty interaction.' },
      ],
      benchmarks: [
        { label: 'Parent Response Rate', val: '86.2%' },
        { label: 'Counseling Conversion', val: '31.5%' },
        { label: 'Cost Per Enrolled Student', val: '₹140' },
      ],
      clientAnchor: 'Apex National Academy',
      clientLocation: 'Acharya Vihar, Bhubaneswar',
    },
  },
  {
    id: 'retail-ecom',
    num: '04',
    title: 'Retail, Fashion & E-commerce D2C',
    shortTitle: 'Retail & D2C',
    category: 'OMNICHANNEL SCALE & ROAS',
    group: 'retail_food',
    tagline: 'Drive walk-ins to your Bhubaneswar showroom and scale your online store pan-India.',
    desc: 'Google Shopping feeds, Instagram dynamic catalog ads, and automated WhatsApp abandoned cart recovery that deliver sustained commercial returns and customer lifetime value.',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1000&q=80',
    color: '#D97706',
    accentBg: 'rgba(217, 119, 6, 0.08)',
    badge: '7.1X VERIFIED ROAS',
    metric: '₹50L+',
    metricLabel: 'Monthly D2C Online GMV',
    services: ['E-commerce Technical SEO', 'Google Shopping & PMax', 'Meta Catalog Retargeting', 'WhatsApp Abandoned Cart Engine'],
    playbook: {
      bottlenecks: [
        'Cart abandonment rate exceeding 70% with zero automated recovery mechanisms in place.',
        'High cost of customer acquisition on Meta ads eating away product profit margins.',
        'Local retail store footfalls stagnating while national e-commerce giants capture market share.',
      ],
      solutions: [
        'Automated 3-stage WhatsApp cart recovery sequences recovering up to 34% of dropped transactions.',
        'Smart Advantage+ catalog campaigns dynamically serving high-converting product variants to in-market buyers.',
        'Hyperlocal store visit ads driving verified footfalls to Janpath, Saheed Nagar, and Patia showrooms.',
      ],
      funnelSteps: [
        { title: 'Lookalike & Catalog Prospecting', desc: 'Target verified online shoppers with dynamic product carousels.' },
        { title: 'Sub-Second Checkout Flow', desc: 'Shopify / Next.js optimized checkouts with UPI 1-click payment.' },
        { title: 'WhatsApp VIP Retention', desc: 'Automated repeat purchase triggers and exclusive loyalty previews.' },
      ],
      benchmarks: [
        { label: 'Blended ROAS', val: '7.1X' },
        { label: 'Cart Recovery Rate', val: '34.2%' },
        { label: 'Repeat Buyer Rate', val: '41.8%' },
      ],
      clientAnchor: 'Divine Fresh & Utkal Crafts',
      clientLocation: 'Janpath & Saheed Nagar, Bhubaneswar',
    },
  },
  {
    id: 'hospitality',
    num: '05',
    title: 'Hospitality, Dining & Tourism',
    shortTitle: 'Hospitality',
    category: 'EXPERIENCE & VIRAL REACH',
    group: 'retail_food',
    tagline: 'Turn your restaurant, cafe, or boutique resort into the city’s top weekend destination.',
    desc: 'Cinematic food Reels, local creator drops, Google Maps local dominance, and WhatsApp table reservations that ensure packed seatings and record weekend footfalls.',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80',
    color: '#EC4899',
    accentBg: 'rgba(236, 72, 153, 0.08)',
    badge: '50K+ ORGANIC REEL VIEWS',
    metric: '3.4X',
    metricLabel: 'Weekend Table Reservations',
    services: ['Cinematic Food Reel Production', 'Odisha Creator Collaborations', 'Google Maps Reviews Moat', '1-Click WhatsApp Table Booking'],
    playbook: {
      bottlenecks: [
        'Weekday tables remaining empty despite heavy weekend footfalls.',
        'Reliance on food delivery aggregators charging 25-30% commissions per order.',
        'Lack of viral visual content showcasing the dining atmosphere and signature dishes.',
      ],
      solutions: [
        'High-production 4K food Reels spotlighting culinary craftsmanship, chef specials, and aesthetic interiors.',
        'Hyperlocal weekday lunch and corporate dining campaigns targeting IT parks in Infocity and Chandrasekharpur.',
        'Direct WhatsApp table reservation system offering exclusive perks and eliminating aggregator fees.',
      ],
      funnelSteps: [
        { title: 'Cinematic Reel Hook', desc: 'Captivate local foodies on Instagram with mouth-watering signature preparation shots.' },
        { title: '1-Tap Menu & Location', desc: 'Direct link to interactive mobile menu and Google Maps navigation.' },
        { title: 'WhatsApp Reservation Confirmation', desc: 'Automated table booking with VIP seating confirmations.' },
      ],
      benchmarks: [
        { label: 'Average Reel Reach', val: '54,000+' },
        { label: 'Direct Booking Lift', val: '+240%' },
        { label: 'Weekday Occupancy', val: '78.5%' },
      ],
      clientAnchor: 'Heritage Bistro & Coastal Kitchen',
      clientLocation: 'Patia & Puri Circuit, Odisha',
    },
  },
  {
    id: 'construction',
    num: '06',
    title: 'Construction & Infrastructure',
    shortTitle: 'Construction',
    category: 'COMMERCIAL RFQ VISIBILITY',
    group: 'b2b_industrial',
    tagline: 'Win commercial contracts, government tenders, and private infrastructure projects in Odisha.',
    desc: 'B2B LinkedIn marketing, authority web engineering, and commercial keyword rankings that position your firm as the trusted infrastructure partner for major developers.',
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?auto=format&fit=crop&w=1000&q=80',
    color: '#0284C7',
    accentBg: 'rgba(2, 132, 199, 0.08)',
    badge: 'TOP 3 B2B SERP RANK',
    metric: '+180%',
    metricLabel: 'Commercial RFQ Inquiries',
    services: ['B2B Technical SEO Schema', 'Corporate Infrastructure Portals', 'LinkedIn Executive B2B', 'RFQ Estimator Funnels'],
    playbook: {
      bottlenecks: [
        'Outdated corporate websites that look abandoned and fail to showcase mega-project engineering capabilities.',
        'Missing out on high-value commercial tenders because corporate decision makers cannot find the company online.',
        'Zero inbound RFQs from national developers expanding into Odisha.',
      ],
      solutions: [
        'Sub-second Next.js corporate portal highlighting project portfolios, technical equipment, and safety certifications.',
        'B2B SEO ranking for commercial terms like "Commercial Contractors Bhubaneswar" and "Industrial PEB Builders Odisha".',
        'Targeted LinkedIn account-based marketing connecting directly with project directors and procurement heads.',
      ],
      funnelSteps: [
        { title: 'Authority Proof Positioning', desc: 'Case study dossiers detailing past commercial square footage and government certifications.' },
        { title: 'Interactive RFQ Estimator', desc: 'Allow corporate developers to submit architectural project specs directly.' },
        { title: 'Executive Follow-up Protocol', desc: 'Automated executive notification with complete technical brief.' },
      ],
      benchmarks: [
        { label: 'Commercial Contract Value', val: '₹14Cr+' },
        { label: 'Organic SERP Position', val: '#1 in Odisha' },
        { label: 'Page Load Speed', val: '< 0.6s' },
      ],
      clientAnchor: 'Kalinga Steel & Infra Projects',
      clientLocation: 'Chandrasekharpur & Mancheswar, Bhubaneswar',
    },
  },
  {
    id: 'professional-services',
    num: '07',
    title: 'Professional Services, CA & Legal',
    shortTitle: 'Legal & CA',
    category: 'EXECUTIVE TRUST & ADVISORY',
    group: 'b2b_industrial',
    tagline: 'Generate high-ticket corporate retainers for CA firms, corporate lawyers, and enterprise consultants.',
    desc: 'Thought-leadership content, executive search intent ads, and high-trust landing pages that establish undeniable authority and convert enterprise clients in Bhubaneswar.',
    image: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=1000&q=80',
    color: '#334155',
    accentBg: 'rgba(51, 65, 85, 0.08)',
    badge: 'ENTERPRISE RETAINERS',
    metric: '42+',
    metricLabel: 'Corporate Retainer Inquiries',
    services: ['High-Intent Search Ads', 'Executive LinkedIn Thought Leadership', 'Corporate Tax & Legal SEO', 'High-Trust Conversion Landers'],
    playbook: {
      bottlenecks: [
        'Relying entirely on word-of-mouth while newly formed startups and enterprises seek advisory online.',
        'Generic websites that do not reflect the specialized tax, compliance, or corporate litigation expertise.',
        'Low consultation conversion rates due to cumbersome booking processes.',
      ],
      solutions: [
        'Targeted Google Search campaigns capturing commercial searches like "Corporate Tax Consultant Bhubaneswar".',
        'Executive LinkedIn thought leadership positioning partners as the premier authority on Odisha state tax policies.',
        'Frictionless consultation scheduling system with instant calendar booking and pre-call qualification.',
      ],
      funnelSteps: [
        { title: 'Executive Intent Sniping', desc: 'Capture business owners searching for GST, compliance, and corporate legal audits.' },
        { title: 'Authority Advisory Dossier', desc: 'Present verifiable case histories and partner credentials with zero corporate fluff.' },
        { title: 'VIP Consultation Scheduling', desc: 'Direct calendar integration booking 30-minute partner strategy calls.' },
      ],
      benchmarks: [
        { label: 'Corporate Client Retainers', val: '42 Active' },
        { label: 'Consultation Conversion', val: '38.6%' },
        { label: 'Average Retainer Value', val: '₹65,000/Mo' },
      ],
      clientAnchor: 'Apex Legal & Tax Advisors',
      clientLocation: 'Saheed Nagar & Jaydev Vihar, Bhubaneswar',
    },
  },
  {
    id: 'manufacturing',
    num: '08',
    title: 'Manufacturing & Industrial Export',
    shortTitle: 'Manufacturing',
    category: 'GLOBAL EXPORT & DOMESTIC SCALE',
    group: 'b2b_industrial',
    tagline: 'Expand your customer reach from Mancheswar and Rasulgarh industrial estates to global buyers.',
    desc: 'Technical B2B catalog SEO, IndiaMart & TradeIndia integration, digital product pitch decks, and international buyer acquisition funnels that generate sustained bulk orders.',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1000&q=80',
    color: '#B45309',
    accentBg: 'rgba(180, 83, 9, 0.08)',
    badge: 'EXPORT INQUIRIES DOMINANCE',
    metric: '45+',
    metricLabel: 'Global Export Orders / Quarter',
    services: ['Technical Industrial SEO', 'B2B Catalog Engineering', 'Export Directory Optimization', 'International Google Search Campaigns'],
    playbook: {
      bottlenecks: [
        'Heavy dependence on local middlemen and brokers who squeeze manufacturing margins.',
        'Ineffective B2B directory listings that generate spam rather than qualified commercial procurement leads.',
        'Inability to attract international export buyers searching for Indian manufacturing partners.',
      ],
      solutions: [
        'Global SEO targeting procurement managers across North America, Europe, and Southeast Asia.',
        'Interactive digital product catalog with technical CAD specs, material certifications, and MOQs.',
        'Geo-targeted Google Search campaigns across target export markets highlighting Indian price advantages.',
      ],
      funnelSteps: [
        { title: 'Global Procurement Intent', desc: 'Target industrial search terms like "Precision CNC Machining India" and "Mineral Export Odisha".' },
        { title: 'Technical Specification Portal', desc: 'Allow buyers to download material test reports and request custom container quotes.' },
        { title: 'Export Deal Structuring', desc: 'Automated CRM routing to export managers with CIF/FOB pricing templates.' },
      ],
      benchmarks: [
        { label: 'Export Inquiries Lift', val: '+280%' },
        { label: 'Direct Deal Margin Lift', val: '+18.4%' },
        { label: 'Average Container Order', val: '₹35L+' },
      ],
      clientAnchor: 'Utkal Precision & Metals',
      clientLocation: 'Mancheswar Industrial Estate, Bhubaneswar',
    },
  },
  {
    id: 'automotive',
    num: '09',
    title: 'Automotive Dealerships & EV Showrooms',
    shortTitle: 'Automotive',
    category: 'HYPERLOCAL TEST DRIVES',
    group: 'retail_food',
    tagline: 'Drive showroom footfall and test-drive bookings across Bhubaneswar with precision geo-fenced campaigns.',
    desc: 'Precision geo-fenced Google Ads, Meta video campaigns, Google Maps 3-Pack rank, and dynamic remarketing that turn car and EV buyers into confirmed showroom appointments.',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1000&q=80',
    color: '#EA580C',
    accentBg: 'rgba(234, 88, 12, 0.08)',
    badge: '320+ TEST DRIVES / MO',
    metric: '320+',
    metricLabel: 'Verified Test Drive Bookings',
    services: ['Geo-Fenced Showroom Ads', '1-Click Test Drive Bookers', 'Google Maps 3-Pack Dominance', 'Dynamic Vehicle Remarketing'],
    playbook: {
      bottlenecks: [
        'High cost per lead with generic portal aggregators who provide duplicate or outdated phone numbers.',
        'Potential buyers researching vehicles online but walking into a competitor dealership closer to their home.',
        'Slow follow-ups resulting in lost showroom walk-ins during festive buying cycles.',
      ],
      solutions: [
        'Hyperlocal geo-fencing within a 15km radius of Bhubaneswar showrooms serving video walkarounds.',
        '1-click WhatsApp test-drive booking widget with instant automated SMS calendar confirmations.',
        'Dynamic remarketing showing buyers the exact vehicle model, color variant, and EMI breakdown they viewed.',
      ],
      funnelSteps: [
        { title: 'Geo-Targeted Video Ad', desc: 'Showcase vehicle acceleration, features, and festive discount offers.' },
        { title: 'Instant WhatsApp Test Drive Booking', desc: 'Buyer selects date, time, and doorstep or showroom test drive preference.' },
        { title: 'Sales Consultant Handover', desc: 'Instant CRM push to showroom manager with designated test-drive vehicle prepped.' },
      ],
      benchmarks: [
        { label: 'Test Drive to Booking Rate', val: '32.8%' },
        { label: 'Cost Per Test Drive Lead', val: '₹195' },
        { label: 'Monthly Vehicle Deliveries', val: '65+ Units' },
      ],
      clientAnchor: 'Odisha EV Motors & Premium Auto',
      clientLocation: 'Khandagiri & Cuttack Road, Bhubaneswar',
    },
  },
  {
    id: 'tech-saas',
    num: '10',
    title: 'IT Services, Software & SaaS',
    shortTitle: 'Tech & SaaS',
    category: 'DEMO PIPELINE & MRR ACCELERATION',
    group: 'tech_logistics',
    tagline: 'Scale software demo bookings, trial signups, and enterprise IT contracts worldwide.',
    desc: 'Product-led content engines, high-converting SaaS landing pages, technical SEO clusters, and LinkedIn ABM funnels that convert tech buyers into recurring software revenue.',
    image: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1000&q=80',
    color: '#0B2093',
    accentBg: 'rgba(11, 32, 147, 0.08)',
    badge: '84% DEMO-TO-TRIAL RATE',
    metric: '4.8X',
    metricLabel: 'Monthly Demo Pipeline Value',
    services: ['SaaS Product Landing Pages', 'Technical Topic Cluster SEO', 'LinkedIn Account-Based Marketing', 'Automated Demo Funnels'],
    playbook: {
      bottlenecks: [
        'Low conversion rates on complex software pages due to overly technical jargon and confusing CTAs.',
        'High trial churn rates because users are not properly onboarded during the first 48 hours.',
        'Struggling to stand out against venture-backed global software competitors on organic search.',
      ],
      solutions: [
        'Conversion-engineered landing pages with interactive product tours and clear ROI calculation meters.',
        'Top-of-funnel technical guides and comparative SEO pages ("X vs Y Alternative") capturing high-intent searchers.',
        'Automated onboarding email and WhatsApp sequences increasing trial activation by 68%.',
      ],
      funnelSteps: [
        { title: 'High-Intent Problem Search', desc: 'Rank #1 for problem-solution queries like "Automated Billing Software for Healthcare".' },
        { title: 'Interactive Product Demo', desc: 'Frictionless 3-minute interactive sandbox allowing buyers to experience core value.' },
        { title: 'Enterprise Trial Onboarding', desc: 'Dedicated customer success onboarding sequence ensuring product stickiness.' },
      ],
      benchmarks: [
        { label: 'Trial Activation Rate', val: '68.4%' },
        { label: 'Demo-to-Closed Rate', val: '34.2%' },
        { label: 'Customer CAC Payback', val: '< 3.2 Months' },
      ],
      clientAnchor: 'CloudSync Solutions & Travysys',
      clientLocation: 'Infocity & DLF Cybercity, Bhubaneswar',
    },
  },
  {
    id: 'agriculture-food',
    num: '11',
    title: 'Agriculture, Dairy & Food Processing',
    shortTitle: 'Agro & Food',
    category: 'DISTRIBUTOR PIPELINE & RETAIL REACH',
    group: 'retail_food',
    tagline: 'Scale distributor networks, modern trade placement, and farm-to-table consumer demand.',
    desc: 'Supply-chain lead generation, regional wholesale distributor funnels, packaging storytelling, and regional D2C e-commerce for Odisha’s agricultural and dairy leaders.',
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1000&q=80',
    color: '#059669',
    accentBg: 'rgba(5, 150, 105, 0.08)',
    badge: '4.8X DISTRIBUTOR NETWORK',
    metric: '180+',
    metricLabel: 'Active Retail Distributors Signed',
    services: ['Distributor Acquisition Funnels', 'Farm-to-Fork Brand Storytelling', 'Regional Trade SEO', 'Direct Consumer Delivery Funnels'],
    playbook: {
      bottlenecks: [
        'Finding it difficult to expand beyond local district boundaries into pan-Odisha retail shelves.',
        'Consumer hesitation regarding freshness, organic purity, and cold-chain integrity.',
        'Manual distributor onboarding leading to slow inventory turnover and missed seasonal demand.',
      ],
      solutions: [
        'Distributor acquisition campaigns across Odisha, West Bengal, and Andhra Pradesh securing verified channel partners.',
        'Video documentary campaigns highlighting ethical dairy farming, clean processing, and certified testing standards.',
        'Local quick-commerce integration and direct subscription funnels for fresh daily deliveries.',
      ],
      funnelSteps: [
        { title: 'Distributor Opportunity Portal', desc: 'Showcase margin structures, territory exclusivity, and marketing support to wholesale distributors.' },
        { title: 'Purity & Origin Video Campaigns', desc: 'Build consumer pull with cinematic farm-origin documentary snippets.' },
        { title: 'Direct Subscription Delivery', desc: 'Allow Bhubaneswar families to subscribe to daily farm-fresh dairy via WhatsApp.' },
      ],
      benchmarks: [
        { label: 'Distributor Onboarding Time', val: '-54%' },
        { label: 'Daily Delivery Subscriptions', val: '2,400+ Homes' },
        { label: 'Retail Shelf Turnaround', val: '3.6X Faster' },
      ],
      clientAnchor: 'Sri Pandurangan Divine Fresh',
      clientLocation: 'Bhubaneswar & Cuttack Green Belt',
    },
  },
  {
    id: 'logistics-supply',
    num: '12',
    title: 'Logistics, Supply Chain & Warehousing',
    shortTitle: 'Logistics',
    category: 'FLEET CONTRACTS & WAREHOUSING',
    group: 'tech_logistics',
    tagline: 'Secure long-term enterprise fleet contracts and fill warehouse square footage in Odisha.',
    desc: 'Commercial freight SEO, enterprise 3PL LinkedIn outreach, warehouse availability portals, and commercial RFQ pipelines that keep your fleet and storage facilities at 100% capacity.',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1000&q=80',
    color: '#1D4ED8',
    accentBg: 'rgba(29, 78, 216, 0.08)',
    badge: '-48% COST PER FLEET CONTRACT',
    metric: '94%',
    metricLabel: 'Warehouse Capacity Utilization',
    services: ['Commercial Freight SEO', '3PL Enterprise LinkedIn ABM', 'Warehouse Real-Time Portals', 'B2B Logistics RFQ Engines'],
    playbook: {
      bottlenecks: [
        'Empty warehouse square footage during non-peak quarters eating into operating profits.',
        'Relying on spot freight brokers who take high cuts and delay settlement payments.',
        'Enterprise manufacturers unaware of modern warehousing and cold storage facilities near NH-16.',
      ],
      solutions: [
        'Dedicated B2B search campaigns ranking for "Warehousing Space in Bhubaneswar" and "Cold Storage Facility Odisha".',
        'LinkedIn account-based outreach connecting directly with FMCG, e-commerce, and pharma supply chain directors.',
        'Interactive warehouse capacity calculator allowing enterprises to reserve square footage with instant rate cards.',
      ],
      funnelSteps: [
        { title: 'Supply Chain Intent Targeting', desc: 'Capture enterprise logistics heads looking for regional distribution centers near Bhubaneswar.' },
        { title: 'Virtual Warehouse Inspection', desc: 'High-res 3D virtual tour showcasing dock levelers, fire safety, and 24/7 CCTV surveillance.' },
        { title: 'Direct Contract Execution', desc: 'Pre-formatted commercial lease agreements and SLA pricing calculator.' },
      ],
      benchmarks: [
        { label: 'Enterprise Contract Value', val: '₹8.5Cr+' },
        { label: 'Warehouse Space Filled', val: '1,20,000 Sq.Ft' },
        { label: 'Cost Per Corporate Contract', val: '-48%' },
      ],
      clientAnchor: 'Kalinga Logistics Hub & 3PL',
      clientLocation: 'Rasulgarh & NH-16 Corridor, Bhubaneswar',
    },
  },
];

export const sectorBenchmarksTicker = [
  { sector: 'Real Estate', metric: '90+ Inbound Buyers/Mo', color: '#0B2093' },
  { sector: 'Healthcare', metric: '+190% Direct Patient Calls', color: '#059669' },
  { sector: 'Higher Education', metric: '₹140 CPL Admissions', color: '#4F46E5' },
  { sector: 'Retail & D2C', metric: '7.1X Verified ROAS', color: '#D97706' },
  { sector: 'Hospitality', metric: '50K+ Food Reel Reach', color: '#EC4899' },
  { sector: 'Construction', metric: '+180% Commercial RFQs', color: '#0284C7' },
  { sector: 'Professional / CA', metric: 'Top 3 B2B SERP Rank', color: '#334155' },
  { sector: 'Manufacturing', metric: '45+ Global Export Orders', color: '#B45309' },
  { sector: 'Automotive', metric: '320+ Test Drives/Mo', color: '#EA580C' },
  { sector: 'Tech & SaaS', metric: '84% Demo-to-Trial Rate', color: '#0B2093' },
  { sector: 'Agro & Food', metric: '4.8X Distributor Network', color: '#059669' },
  { sector: 'Logistics', metric: '94% Warehouse Occupancy', color: '#1D4ED8' },
];

export const sectorCorridorMatrix = [
  {
    corridor: 'Patia & Infocity',
    focus: 'Tech, SaaS, Cafes, High-Ticket Luxury Villas',
    metric: '65,000+ Tech Searches / Mo',
    anchor: 'Utkal Heights & Travysys',
    badge: 'HIGH-TICKET HUB',
  },
  {
    corridor: 'Saheed Nagar',
    focus: 'Healthcare, Speciality Clinics, CA & Legal',
    metric: '42,000+ Patient Calls / Mo',
    anchor: 'CareFirst Multi-Speciality',
    badge: 'HEALTHCARE CORRIDOR',
  },
  {
    corridor: 'Chandrasekharpur',
    focus: 'Higher Education, Competitive Coaching, B2B Infra',
    metric: '85,000+ Student Searches / Mo',
    anchor: 'Apex National Academy',
    badge: 'EDUCATION MOAT',
  },
  {
    corridor: 'Khandagiri & Nayapalli',
    focus: 'Automotive Dealerships, EV Showrooms, Retail',
    metric: '38,000+ Test Drive Queries',
    anchor: 'Odisha EV Motors',
    badge: 'AUTOMOTIVE BELT',
  },
  {
    corridor: 'Mancheswar & Rasulgarh',
    focus: 'Industrial Manufacturing, 3PL Logistics, Warehousing',
    metric: '28,000+ Commercial RFQs',
    anchor: 'Kalinga Steel & Logistics',
    badge: 'INDUSTRIAL GATEWAY',
  },
  {
    corridor: 'Puri Circuit & Cuttack Road',
    focus: 'Hospitality, Dining, Tourism, Agri-Food Supply',
    metric: '92,000+ Tourist & Diner Searches',
    anchor: 'Heritage Bistro & Divine Fresh',
    badge: 'TOURISM ARTERY',
  },
];

export const sectorRoiTiers = [
  {
    sectorId: 'real-estate',
    name: 'Real Estate & Builders',
    minBudget: 50000,
    maxBudget: 250000,
    cplRange: '₹350 – ₹600',
    leadMultiplier: 0.0022,
    pipelineMultiplier: 45,
    channelSplit: '50% Google Search • 30% Meta Virtual Tours • 20% WhatsApp CRM',
  },
  {
    sectorId: 'healthcare',
    name: 'Healthcare & Clinics',
    minBudget: 30000,
    maxBudget: 150000,
    cplRange: '₹120 – ₹250',
    leadMultiplier: 0.0055,
    pipelineMultiplier: 18,
    channelSplit: '60% Google Maps 3-Pack • 25% Meta Doctor Videos • 15% WhatsApp Bot',
  },
  {
    sectorId: 'education',
    name: 'Education & Coaching',
    minBudget: 40000,
    maxBudget: 200000,
    cplRange: '₹140 – ₹280',
    leadMultiplier: 0.0062,
    pipelineMultiplier: 12,
    channelSplit: '45% Meta Lead Ads • 35% YouTube Faculty Drops • 20% WhatsApp Counseling',
  },
  {
    sectorId: 'retail-ecom',
    name: 'Retail & E-commerce D2C',
    minBudget: 35000,
    maxBudget: 300000,
    cplRange: '7.1X ROAS Target',
    leadMultiplier: 0.0075,
    pipelineMultiplier: 8,
    channelSplit: '50% Google Shopping/PMax • 35% Dynamic Meta Catalog • 15% WhatsApp Cart Engine',
  },
  {
    sectorId: 'b2b-industrial',
    name: 'B2B, Infra & Manufacturing',
    minBudget: 50000,
    maxBudget: 250000,
    cplRange: '₹800 – ₹1,500',
    leadMultiplier: 0.0012,
    pipelineMultiplier: 120,
    channelSplit: '55% B2B Technical SEO • 30% LinkedIn ABM • 15% RFQ Web Estimators',
  },
];
